version: "3"

services:
  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  tg_bot:
    image: database:latest
    volumes:
      - sqlite_data:/var/lib/sqlite/data/
  api:
    build: .
    volumes:
      - . :/paysistem46
    ports:
      - "2525:2525"
    command:
      - uvicorn
      - main:app
      -  --host=0.0.0.0
      - --port=2525
    depends_on:
      - database
      - tg_bot
volumes:
  postgres-data: